
dimensionedScalar sigmaK1_  = 0.85;
dimensionedScalar sigmaK2_  = 1.0;

dimensionedScalar sigmaOmega1_ = 0.5;
dimensionedScalar sigmaOmega2_ = 0.856;

dimensionedScalar gamma1_ = 5/9;
dimensionedScalar gamma2_ = 0.44;

dimensionedScalar beta1_ = 0.075;
dimensionedScalar beta2_  = 0.0828;

dimensionedScalar betaStar_ = 0.09;

dimensionedScalar a1_ = 0.31;
dimensionedScalar b1_ = 1.0;
dimensionedScalar c1_ = 10.0;
